# Generated by Django 5.0.4 on 2024-05-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_1', models.TextField(blank=True, null=True)),
                ('redundancies_1', models.TextField(blank=True, null=True)),
                ('inappropriateness_1', models.TextField(blank=True, null=True)),
                ('corrections_1', models.TextField(blank=True, null=True)),
                ('corrected_response_1', models.TextField(blank=True, null=True)),
                ('response_2', models.TextField(blank=True, null=True)),
                ('redundancies_2', models.TextField(blank=True, null=True)),
                ('inappropriateness_2', models.TextField(blank=True, null=True)),
                ('corrections_2', models.TextField(blank=True, null=True)),
                ('corrected_response_2', models.TextField(blank=True, null=True)),
                ('response_3', models.TextField(blank=True, null=True)),
                ('redundancies_3', models.TextField(blank=True, null=True)),
                ('inappropriateness_3', models.TextField(blank=True, null=True)),
                ('corrections_3', models.TextField(blank=True, null=True)),
                ('corrected_response_3', models.TextField(blank=True, null=True)),
                ('response_4', models.TextField(blank=True, null=True)),
                ('redundancies_4', models.TextField(blank=True, null=True)),
                ('inappropriateness_4', models.TextField(blank=True, null=True)),
                ('corrections_4', models.TextField(blank=True, null=True)),
                ('corrected_response_4', models.TextField(blank=True, null=True)),
                ('response_5', models.TextField(blank=True, null=True)),
                ('redundancies_5', models.TextField(blank=True, null=True)),
                ('inappropriateness_5', models.TextField(blank=True, null=True)),
                ('corrections_5', models.TextField(blank=True, null=True)),
                ('corrected_response_5', models.TextField(blank=True, null=True)),
                ('response_6', models.TextField(blank=True, null=True)),
                ('redundancies_6', models.TextField(blank=True, null=True)),
                ('inappropriateness_6', models.TextField(blank=True, null=True)),
                ('corrections_6', models.TextField(blank=True, null=True)),
                ('corrected_response_6', models.TextField(blank=True, null=True)),
                ('response_7', models.TextField(blank=True, null=True)),
                ('redundancies_7', models.TextField(blank=True, null=True)),
                ('inappropriateness_7', models.TextField(blank=True, null=True)),
                ('corrections_7', models.TextField(blank=True, null=True)),
                ('corrected_response_7', models.TextField(blank=True, null=True)),
                ('response_8', models.TextField(blank=True, null=True)),
                ('redundancies_8', models.TextField(blank=True, null=True)),
                ('inappropriateness_8', models.TextField(blank=True, null=True)),
                ('corrections_8', models.TextField(blank=True, null=True)),
                ('corrected_response_8', models.TextField(blank=True, null=True)),
                ('response_9', models.TextField(blank=True, null=True)),
                ('redundancies_9', models.TextField(blank=True, null=True)),
                ('inappropriateness_9', models.TextField(blank=True, null=True)),
                ('corrections_9', models.TextField(blank=True, null=True)),
                ('corrected_response_9', models.TextField(blank=True, null=True)),
                ('response_10', models.TextField(blank=True, null=True)),
                ('redundancies_10', models.TextField(blank=True, null=True)),
                ('inappropriateness_10', models.TextField(blank=True, null=True)),
                ('corrections_10', models.TextField(blank=True, null=True)),
                ('corrected_response_10', models.TextField(blank=True, null=True)),
                ('overall_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
