# Generated by Django 5.0.4 on 2024-05-26 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InterviewAnalyze', '0001_initial'),
        ('QuestionList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanalysis',
            name='question_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionList.questionlists'),
        ),
    ]
